name: publish-pypi

on:
  push:
    tags:        
      - '*'
  pull_request:
    branches: [ '*' ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Maturin build
      uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --release
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: target/wheels/


