name: publish-pypi

on:
  push:
    tags:        
      - '*'
  pull_request:
    branches: [ '*' ]
jobs:
  build_and_push:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        cd .github
        docker build -t maturin-cairo-rs-py .
        docker run -e PYPI_API_TOKEN=${{ secrets.PYPI_API_TOKEN }} maturin-cairo-rs-py



