name: publish-pypi

on:
  push:
    tags:        
      - '*'
  pull_request:
    branches: [ '*' ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Setup Pyenv
      uses: "gabrielfalcao/pyenv-action@v9"
      with:
        default: 3.9.7
    - name: Install maturin
      run: pip install maturin
    - name: Maturin build
      run: maturin build --release --target aarch64-apple-darwin
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: target/wheels/


