name: rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Rust 1.69.0
      uses: dtolnay/rust-toolchain@1.69.0
      with:
        components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Setup Pyenv
      uses: "gabrielfalcao/pyenv-action@v9"
      with:
        default: 3.9
    - name: Install test dependencies
      run: make deps-default-version
    - name: Format
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: make clippy
    - name: Build
      run: make build
    - name: Run tests
      run: make full-test
    - name: Compare-Trace-Memory
      run : make run-comparer-tracer
    - name: Coverage
      run: make coverage
    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error:     true
    - name: Cleanup tests
      run: make clean
